### ISSUE TITLE
Out of bounds error

### ISSUE THREAD

**Issue by misan** [earcut4j/earcut4j#1]
I get an out of bounds error when triangulating shapes with a hole. Works ok otherwise.

Caused by: java.lang.ArrayIndexOutOfBoundsException: 2398
	at Earcut.signedArea(Earcut.java:604)
	at Earcut.linkedList(Earcut.java:556)
	at Earcut.earcut(Earcut.java:34)

**Comment by misan** [comment]
My mistake: holeIndex values refer to the vertex number and not to the data array index where the hole starts :-( 

Once I realized that it worked ok.
